kind: pipeline
type: docker
name: default

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc.wetter.land
      tags: latest
      Dockerfile: ./dockerfile
    commands:
    - echo "You can call the secrets like this examples below."
    - echo $USERNAME
    - echo $PASSWORD
    - echo "In both cases, and for security"
