kind: pipeline
type: docker
name: default

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      username: xhelliom
      password: 7xUehHr$9Jjl
      repo: xhelliom/doc.wetter.land
      tags: latest
      Dockerfile: ./dockerfile