kind: pipeline
type: docker
name: default

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc-wetter-land
      tags: 1.0.7
      Dockerfile: ./dockerfile
trigger:
  branch:
  - main2
  event:
    exclude:
    - pull_request