matrix:
  TAG:
    - 1.0.10
    - latest

steps:
  - name: build
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm run build
    when:
      - event: push
        branch: main
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          # limits:
          #   memory: 800Mi
          #   cpu: 800m
  
  - name: publish_amd
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc-wetter-land
      tags: ${TAG}
      Dockerfile: ./dockerfile
    when:
      - event: push
        branch: main
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          # limits:
          #   memory: 400Mi
          #   cpu: 1000m

  - name: publish_arm
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      platforms: linux/arm64/v8,linux/amd64
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc-wetter-land
      tags: ${TAG}
      Dockerfile: ./dockerfile
    when:
      - event: push
        branch: main
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          # limits:
          #   memory: 400Mi
          #   cpu: 1000m
