steps:
  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64/v8
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc-wetter-land
      tags: 1.0.7
      Dockerfile: ./dockerfile
when:
  branch:
  - main