steps:
  - name: build
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: build # script name
      #with: npm # if `with` is set, enforce to use this package manager
      frozen_lockfile: false # not recommended in false
      ignore_node_modules: true # recommended
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 500Mi
            cpu: 400m
          limits:
            memory: 800Mi
            cpu: 800m
  # - name: test
  #   image: codeberg.org/woodpecker-plugins/node-pm
  #   settings:
  #     run: serve # script name
  #     #with: npm # if `with` is set, enforce to use this package manager
  #   backend_options:
  #     kubernetes:
  #       resources:
  #         requests:
  #           memory: 200Mi
  #           cpu: 100m
  #         limits:
  #           memory: 400Mi
  #           cpu: 1000m
  - name: publish_amd
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc-wetter-land
      tags: 1.0.8
      Dockerfile: ./dockerfile
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 400Mi
            cpu: 1000m

  - name: publish_arm
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      platforms: linux/arm64/v8,linux/amd64
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xhelliom/doc-wetter-land
      tags: 1.0.8
      Dockerfile: ./dockerfile
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 400Mi
            cpu: 1000m
